name: Test Setup Alibaba Cloud CLI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Use action
        uses: ./setup-aliyun-cli
        with:
          version: latest

      - name: Verify
        shell: bash
        run: |
          aliyun version
