name: Test Setup Node

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Use Actions
        uses: ./setup-node
        with:
          pnpm-version: '11'
          run-install: 'false'

      - name: Test
        run: |
          node -v
          bun -v
          pnpm -v
